CREATE LARGE TABLESPACE LOBTABLESPACE IN DATABASE 
PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 4096 
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP IBMSTOGROUP AUTORESIZE YES BUFFERPOOL IBMDEFAULTBP OVERHEAD INHERIT TRANSFERRATE INHERIT DROPPED
TABLE RECOVERY
ON DATA TAG INHERIT


CREATE TABLE op.awt_files (
    ID BIGINT NOT NULL,
    NAME VARCHAR(64),
    LAST_UPDT_TIME TIMESTAMP,
    DATA BLOB(1048576) INLINE LENGTH 164 COMPACT,
	LOG_NBR INT,
	TIME_GENERATED TIMESTAMP
    )
    ORGANIZE BY ROW
    DATA CAPTURE NONE
    LONG IN "LOBTABLESPACE"
    COMPRESS NO
	
ALTER TABLE op.awt_files ADD CONSTRAINT awt_files_pk PRIMARY KEY
	(ID)@