DROP TABLE op.gsi_employees@

CREATE TABLE op.gsi_employees (
	EMPLOYEE_ID CHAR(9) NOT NULL,
	EMPLOYEE_NAME VARCHAR(500),
	EMPLOYEE_NOTES_ID VARCHAR(500),
	EMPLOYEE_MAIL_INTERNET VARCHAR(500),
	EMPLOYEE_ROLE VARCHAR(100)
)@

ALTER TABLE op.gsi_employees ADD CONSTRAINT gsi_employees_pk PRIMARY KEY
	(EMPLOYEE_ID)@